### ISSUE TITLE
Doc.: Bad (old?) reference to "Analysis" instead of "AnalysisTemplate"

### ISSUE THREAD

**Issue by dsbos** [argoproj/argo-rollouts#1234]
## Summary 

The page at https://argoproj.github.io/argo-rollouts/architecture refers to Analysis and AnalysisRun resources, and doesn't mention AnalysisTemplate. 

Shouldn't those references to "Analysis" say "AnalysisTemplate"?

## Diagnostics

> What version of Argo Rollouts are you running?

N/A

I'm looking at https://argoproj.github.io/argo-rollouts/architecture/#analysis-and-analysisrun as of 2021-05-28.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
I believe the intent was:

The term "analysis"  broadly refers to the use of canary/metric analysis as part of a rollout update. This should not be uppercased unless it is at a beginning of a sentence or in Title Case.

AnalysisTemplates and AnalysisRuns are the implementations of canary analysis support in Rollouts. Since these are referring to custom resources, it should always be CamelCased, and also with code formatting (e.g. `AnalysisTemplate`)

It looks like we are definitely treating the word Analysis like a CRD in the docs so that should be fixed

**Comment by dsbos** [comment]
>It looks like we are definitely treating the word Analysis like a CRD in the docs so that should be fixed

Note that the capitalized "Analysis" seems to used in several different ways, so yeah, there's some straightening out to do. 

---

Does the type of the value of a `spec.strategy.canary.analysis` member (the invocation of an AnalysisTemplate object(s)) have a name (e.g., a non-top-level object maybe called something like AnalysisSpec or AnalysisCall or something)? 

It would be helpful if Argo Rollouts could eventually document its top-level objects (K8s resource kinds) and their subordinate objects similarly to the way that Istio (and K8s too?) documents its objects and sub-objects (e.g., https://istio.io/latest/docs/reference/config/networking/gateway/#Gateway and https://istio.io/latest/docs/reference/config/networking/gateway/#Server).

In particular, it would make clearer when members/fields in different places are of the same type (e.g., `spec.strategy.canary.analysis` and a `spec.strategy.canary.steps[x].analysis`) and when they're not. (I'm thinking of not-always-clear differences between top-level Experiment objects and the sub-objects in `spec.strategy.canary.steps[x].experiment` members.)
