### ISSUE TITLE
Latest tag used on manifests on released version

### ISSUE THREAD

**Issue by paveq** [argoproj/argo-rollouts#1641]
## Summary 

Latest tag used on manifests on released version for the image.

## Expected result

When installing Rollouts via Kustomize, tag on deployment would point to the version that is requested.

Latest tag is also used in generated manifests: https://github.com/argoproj/argo-rollouts/blob/v1.1.0/manifests/install.yaml#L13149

## Additional information

My Kustomization.yaml looks like:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
- github.com/argoproj/argo-rollouts/manifests/cluster-install?ref=v1.1.0
- namespace.yaml

patchesStrategicMerge:
- patches/setResources.yaml
```

**Comment by jessesuen** [comment]
We no longer commit the install manifests into git with hardwired versions because it complicated the release process. Instead, we attach install manifests to the release. You can change your customization to reference this instead:

https://github.com/argoproj/argo-rollouts/releases/download/v1.1.0/install.yaml
