### ISSUE TITLE
BlueGreen Deployment Strategy should respect `status.HPAReplica` if exists.

### ISSUE THREAD

**Issue by civitaspo** [argoproj/argo-rollouts#1864]
# Summary

* BlueGreen Deployment Strategy should respect `status.HPAReplica` if exists.
    * If in the current implementation `status.HPAReplica` is larger than the `spec.replicas` defined in Rollout, the replicas of the active ReplicaSet will be updated with a smaller value, causing a temporary scale down before switching the new ReplicaSet.
    * This behaviour occurs in phase2. ref. https://argoproj.github.io/argo-rollouts/features/bluegreen/
        * > 2\. A user initiates an update by modifying the pod template (spec.template.spec).
        * ref. https://github.com/argoproj/argo-rollouts/blob/18677425dc2447a3c43683b1bdac3d031e4de6d6/rollout/bluegreen.go#L84

# Use Cases

* No more unnecessary scale down when using Rollout with BlueGreen Deployment Strategy in combination with HPA.

# Related Issues

* https://github.com/kubernetes/kubernetes/issues/25238

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by civitaspo** [comment]
If I can get a good response to this improvement from the maintainers, I'm willing to implement it myself.

**Comment by harikrongali** [comment]
If you have HPA enabled, can you remove replicas from rollout spec & validate.

**Comment by civitaspo** [comment]
@harikrongali Thanks for the info!!! From what I read in the code, I think that if I remove replicas from the Spec of Rollout, it will be treated as replicas=1 by default. So, if the value of `status.HPAReplica` is greater than 1, the replicas of ReplicaSet will be updated with `1` and scale down will occur. Is my understanding wrong?

https://github.com/argoproj/argo-rollouts/blob/1867742/rollout/bluegreen.go#L84
https://github.com/argoproj/argo-rollouts/blob/1867742/pkg/apis/rollouts/v1alpha1/types.go#L39-L42
https://github.com/argoproj/argo-rollouts/blob/1867742/utils/defaults/defaults.go#L81-L86

**Comment by jessesuen** [comment]
> From what I read in the code, I think that if I remove replicas from the Spec of Rollout, it will be treated as replicas=1 by default.

@civitaspo - this is true, but only for the initial setting. The `spec.replicas` will be defaulted to 1 if it is `null`, but after it is set, will not touch the value.

When using Rollouts (or Deployments/StatefulSets) with HPA, the expectation is that you do not specify `spec.replicas` because this value will be controlled by HPA. You should never specify `spec.replicas` if you know you will be using HPA with it.

You can see Kubernetes documentation about this:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling

The docs also apply to Rollouts.

**Comment by civitaspo** [comment]
I see. I understand that the unexpected scale down was happening because we had explicitly specified `replicas` even though we use HPA in our environment. Thank you for your help.
