### ISSUE TITLE
JSON Logging

### ISSUE THREAD

**Issue by DWSR** [argoproj/argo-rollouts#1914]
# Summary

Argo Rollouts is one of the few Argo projects that doesn't support JSON logging

# Use Cases

When trying to naively parse logs using a log aggregator like Fluentd.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by hcelaloner** [comment]
I am not sure since I didn't use it. However, it seems that the controller provides flags to change log format: https://github.com/argoproj/argo-rollouts/blob/master/cmd/rollouts-controller/main.go#L221

Therefore, I don't know whether it is documented or not but passing additional command-line arguments to the rollouts-controller may change its log format.

**Comment by perenesenko** [comment]
@DWSR 
yes, that's correct `--logformat=json` will work.
We just need to fix a documentation

**Comment by AliDotS** [comment]
When leader election is enabled there is one line that doesn't follow JSON format.
`12:08:56.641662       1 leaderelection.go:248] attempting to acquire leader lease argocd/argo-rollouts-controller-lock...`

**Comment by DWSR** [comment]
Not stale.

**Comment by Sineaggi** [comment]
Not stale.

**Comment by DWSR** [comment]
Not stale.

**Comment by Sineaggi** [comment]
@AliDotS presumably logs from klog aren't being mapped to logrus.
