### ISSUE TITLE
Replica count not maintained during canary rollout

### ISSUE THREAD

**Issue by SriranjithaR** [argoproj/argo-rollouts#1966]
# Summary
We are running a canary argo rollout. We have set the `spec.replicas` count to 24. 
The rollout spec has 3 steps: 
```
      rollout:
        steps:
        - setWeight: 5
        - pause: {}
        - setWeight: 100
```
During the first step (deploying 5% canary), we see that there are atleast 24 pods (stable+canary) serving traffic at all times. However, in step 3, we observed that stable pods are taken down before canary pods have all their containers ready.
Almost obviously, we observe that the startupProbe endpoints haven't succeeded yet on the canary's containers when the stable pods have already been taken down.

Because of this, we end up having fewer pods serving traffic than required for a period of time.
![image](https://user-images.githubusercontent.com/13716407/162257800-025091cd-761d-4360-8bc1-b144e3a41765.png)

What can be the cause for this?

## Expected results
There should be at least the #replicas (i.e 24) pods with ready containers at all times.

## Actual results
There are fewer than 24 pods with ready containers during the rollout process.

# Diagnostics
What version of Argo Rollouts are you running?
kubectl-argo-rollouts: v1.0.7+1d8052e

**Comment by perenesenko** [comment]
Hi @SriranjithaR 
It's expected behavior.
Once switching weight from 5% => 100% the Rollout decreasing stable for the `maxUnavailable` 25% and increasing the canary for `maxSurge` 25%.

If you don't want the total number goes below the 24 pods you can specify `maxUnavailable` = 0

See: https://argoproj.github.io/argo-rollouts/features/canary/#maxunavailable
