### ISSUE TITLE
Argo Rollouts should recognize and kill stuck pods

### ISSUE THREAD

**Issue by MarkSRobinson** [argoproj/argo-rollouts#1980]
# Summary

Occasionally, a pod will be unable to progress to the healthy state.  This will cause the rollout to timeout because it cannot progress.

It would be useful if argo could recognize that (1) there aren't enough healthy pods in the rollouts (2) pods are unable to become healthy soon enough that argo times out, (3) delete the pods so that they are recreated and restarted.

# Use Cases

I had a case today where a rollout got stuck on a misbehaving pod.  Deleting the pod fixed the issue, but it would be nice if the rollout controller could do it for me.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
So I have questions was the un-healthy pod on the stable replicaset or canary replicaset? The reason I ask is because this [PR](https://github.com/argoproj/argo-rollouts/pull/1957) might help this situation if it was on the stable. I also feel that the Rollouts controller should not deal much with the pods and that should be left to the Kubernetes replicaset controller which will restart pods that are failing their health check already.

**Comment by MarkSRobinson** [comment]
@zachaller It's on the canary pod set

**Comment by MarkSRobinson** [comment]
Someone just reported that the pods were in the stable replica-set too

**Comment by zachaller** [comment]
@MarkSRobinson The pr mentioned above will fix the stable replica set case for sure however as far as the canary rs it really should be up to the k8s replica set controller to kill any pods not passing their liveness check. Was a liveness check defined?
