### ISSUE TITLE
High reconciliation activity and CPU load for invalid rollout

### ISSUE THREAD

**Issue by Cylix** [argoproj/argo-rollouts#2023]
## Summary 

We mistakenly configured an invalid rollout, by using `setCanaryScale` without enabling Traffic Routing:

```
  canary:
    steps:
      - setCanaryScale:
           replicas: 2
```

ArgoCD was able to sync, but argo-rollout failed to progress with the following error:

```
time="2022-05-05T19:28:40Z" level=error msg="The Rollout \"hello-pagey-argo\" is invalid: spec.strategy.steps[0].setCanaryScale: Invalid value: v1alpha1.SetCanaryScale{Weight:(*int32)(nil), Replicas:(*int32)(0xc0000e787c), MatchTrafficWeight:false}: SetCanaryScale requires TrafficRouting to be set" namespace=hello-pagey-argo rollout=hello-pagey-argo
```

While the error was expected, this also resulted in a very high reconciliation activity and high CPU load:

![Screen Shot 2022-05-06 at 1 24 01 PM](https://user-images.githubusercontent.com/3252462/167211656-84ce9e16-8f63-41d9-a3fe-42cfaa433a6b.png)

![Screen Shot 2022-05-06 at 1 24 07 PM](https://user-images.githubusercontent.com/3252462/167211657-d9017e87-948d-4f1f-a08d-cbf21a4abdb7.png)

It seems like the argo-rollout controller was  infinitely retrying to apply the faulty rollout configuration without any backoff. We tried to find some configuration option to leave some delays between retries, but didn't find any, though I'd be happy to implement something if you feel that's relevant 🤔 

## Diagnostics

Argo Rollouts version: `v1.2.0+08cf10e`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
During the investigation I found the reason. After reconciliation is done we're immediately calling for a new reconciliation in case if the status _message_ field changed.

The error message we have every time has a different text as we're displaying the address of a `Replicas` field rather than a value
For example the next message has Replicas:(*int32)(0xc000a8936c) value with the address.
> InvalidSpec: The Rollout "rollouts-demo" is invalid: spec.strategy.steps[0].setCanaryScale: Invalid value: v1alpha1.SetCanaryScale{Weight:(*int32)(nil), Replicas:(*int32)(0xc000a8936c), MatchTrafficWeight:false}: SetCanaryScale requires TrafficRouting to be set

In general, the error is displayed in a _status.condition.message_ field is not causing any repetitive reconciliations. But in our case the error message different every time and this causing repetitive recondilations.
