### ISSUE TITLE
Breaking change with v1.4: experiment k8s service created even if steps are not weighted

### ISSUE THREAD

**Issue by fwippe** [argoproj/argo-rollouts#2622]
Checklist:

* [x] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**
Even for simple experiments, i.e.,  without any weighted steps, Argo always creates corresponding k8s services.
This behavior was introduced with [this PR](https://github.com/argoproj/argo-rollouts/pull/2397). According to the [docs](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/experiment.md#weighted-experiment-step-with-traffic-routing) a service should only be created if there are weighted experiment steps.

Can you maybe elaborate on the reasons for this breaking change? Why do you always create a k8s service even if it's not needed?

*Why is this a breaking change?*

After upgrading to version 1.4, suddenly experiments were failing with different error messages complaining about missing or invalid k8s service properties (like `service name too long (> 63 chars)` or `missing port name attribute`).

**Expected behavior**
- Argo rollouts should not create an additional experiment service if there are no weighted experiment steps

**Version**
v1.4.0

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
@fwippe Yea that was a big miss on my part sorry for the change in behavior, I have been talking with alex and dani who originally had the request for a use case they had which does make sense. We tried to do the change in a non spec changing way which resulted in this change in behavior. 

The plan is going forward will be to revert the change in behavior in a 1.4.1  release that I will be doing here soon to keep the expected behavior and look into possible other solutions to support always creating services for inline experiments all the time.

I will be noting in the release notes for 1.4.1 that there was an unintended change in behavior that was reverted for 1.4.1 as well.
