### ISSUE TITLE
CLI watch command showing blue/green colors backwards

### ISSUE THREAD

**Issue by domenicbove** [argoproj/argo-rollouts#3066]
# Summary

When I run `kubectl argo rollouts get rollout <rollout-name> --watch` it shows the `preview` revision in blue font and the `stable,active` in green font. This is backwards if I understand blue/green deployments. I would expect the new/preview revision to be green and the stable to be blue

# Use Cases

When would you use this?

This isn't pressing, I use the `--watch` flag for demos. It does not impact the core functionality I need.
Figured this would be an easy fix on your end

Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by Dashhh** [comment]
Hey, I would like to take this issue as my first contribution to Argo project :blush:

**Comment by zachaller** [comment]
I don't think colors really have much meaning I spent a bit of time looking around and both get used for "stable". I kind of like green as stable because green generally means good or healthy which I equate to stable.

https://stackoverflow.com/questions/60412841/reason-for-the-colors-blue-and-green-in-blue-green-deployment

**Comment by domenicbove** [comment]
We used "greenfield" deployment a lot in my last company, I always thought "green" is new (and leaving blue to be old)! Sounds like there isn't a consensus. Thanks for sharing that. Feel free to close this!

**Comment by zachaller** [comment]
No problem it's is interesting that there is no concensus
