### ISSUE TITLE
Why changed the way to promote new version Pod with BlueGreen strategy

### ISSUE THREAD

**Issue by ShotaKitazawa** [argoproj/argo-rollouts#307]
I'm using BlueGreen strategy in Argo Rollouts.

In v0.4.1, I deployed BlueGreen Rollouts Resource with `.Spec.Strategy.BlueGreen.AutoPromotionEnabled: false` and executed below due to promote new version Pod.

```
kubectl patch rollouts/NAME --patch '{"spec": {"paused": false}}' --type merge
```

In v0.6.0, this patch command is not active. Because, I look like that condition controller watched is change to below in #211.

* in #221
    * old: `Spec.Paused` 
    * new: `len(Status.PauseConditions) > 0`

Thus, I understood to execute below due to promote new version Pod.

```
# patch
kubectl patch rollouts/NAME --patch '{"status": {"pauseConditions": []}}' --type merge
```

or 

```
# using argo-rollouts kubectl plugin
kubectl argo rollouts promote NAME
```

I want to know why this change. thank you.

**Comment by jessesuen** [comment]
We needed a way to distinguish between user specified pauses vs. controller specified pauses. With a single spec.paused field, it was not possible to discern the two types.

In v0.4 and v0.5, we were not honoring user specified pauses with the canary strategy. By having user vs. controller initiated pauses, we can now support honoring user specified pause but also "reset" the pause when things like the pod spec changes.

**Comment by ShotaKitazawa** [comment]
sorry, I cant figure out "reset".

Does "reset" mean that new pod is not promoted when canary analysis promote new pod after user executed `kubectl argo rollouts pause pause NAME`?

**Comment by jessesuen** [comment]
Reset just means unsetting the pause when the spec changes. Lets say you have a rollout strategy that has a pause step, e.g.:

```yaml
steps:
- setWeight: 10
- pause: {}
```

And it reaches the second step. If at that point you apply a new manifest with a new version, the expectation is that the rollout should restart the rollout to the new version. This is what we refer to as a controller initiated pause.

On the other, if a user manually paused a rollout by setting `spec.paused: true`, then we should honor that until explicitly unset by the user. This is a user initiated pause. The bug was that we were not honoring user initiated pauses.

> Does "reset" mean that new pod is not promoted when canary analysis promote new pod after user executed kubectl argo rollouts pause pause NAME?

Correct. Now in v0.6 if a user sets spec.paused to be true, we should not progress the rollout. Note that we will still scale the rollout if the spec.replicas is modified (e.g. in the case of HPA, or manually).

**Comment by ShotaKitazawa** [comment]
Thank you for your reply! I was able to understand.
