### ISSUE TITLE
Abort status not reset for bluegreen deployments

### ISSUE THREAD

**Issue by thatsmydoing** [argoproj/argo-rollouts#313]
After aborting a bluegreen rollout, subsequent updates to the rollout remain in an aborted state. The new rollout seems to proceed as normal but the aborted flag remains true.

**Comment by dthomson25** [comment]
The abort status is reset now with the following change: https://github.com/argoproj/argo-rollouts/pull/314/files#diff-cfad87918ee0d3175ebd8e47f5efd159R233, but there's a larger issue at hand with https://github.com/argoproj/argo-rollouts/issues/316. 

Since this issue was addressed by the PR listed above, and we have a separate issue for integrating the abort field with the bluegreen strategy, I am going to close this ticket.
