### ISSUE TITLE
[improvement] Install manifest

### ISSUE THREAD

**Issue by ltagliamonte-dd** [argoproj/argo-rollouts#334]
Hi there, based on your [doc](https://argoproj.github.io/argo-rollouts/)  we noticed that the main manifest declares multiple ClusterRoles:
- argo-rollouts-aggregate-to-admin
- argo-rollouts-aggregate-to-edit
- argo-rollouts-aggregate-to-view
- argo-rollouts-clusterrole

but effectively creates 1 ClusterRoleBinding that uses argo-rollouts-clusterrole

Would it be possible to remove the unused ClusterRoles from the main install manifest?
Would also be nice don't mangle all the manifests in a single install manifest, due the fact that debug and audit of it is really difficult, would it be an option to have the a helm chart instead?

Me or someone on my team would love to help and work on those requests, if the maintainers accept.
Nowadays we are maintaining an internal fork but keep it in sync with the upstream is becoming cumbersome.

**Comment by jessesuen** [comment]
The aggregate roles are necessary to give the built in **_namespace_** admins (note: I am not referring to cluster admins), the ability to manage rollouts. See https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles.

So in other words, they need to exist be kept because without this, a namespace admin could not get/update/create rollout objects. That said, the `aggregate-to-edit` and `aggregate-to-admin` are the same, and I think they can be combined to a single role which has both annotations.

The install.yaml is meant for easier instructions getting started. The individual components can be deployed individually so you could piece-meal your installation if you need.

I will use this issue to rework the install manifests, since I recently noticed there are unnecessary namespaced Role: `argo-rollouts-role`, RoleBinding: `argo-rollouts-role-binding`. This was originally included to allow Argo Rollouts to operate on a single namespace, which is no longer be possible since we now have a requirement to list ClusterAnalysisTemplates (which require cluster roles).
