### ISSUE TITLE
Migrating from a ArgoCD Deployment to an Argo Rollouts Resource

### ISSUE THREAD

**Issue by tomsanbear** [argoproj/argo-rollouts#335]
If I currently have a Kubernetes Deployment managed by ArgoCD, and want to convert it to a rollout, will this require me to manually delete the old Deployment resource after changing the resource type (as referenced in the docs), or is this migration behaviour handled by Rollouts?

Apologies if this is answered/obvious somewhere, I am relatively new to ArgoCD tooling.

Thanks!

**Comment by carlosdoordash** [comment]
As of 0.6.2, Argo Rollouts does not automatically delete the old Deployment resource. For migrating from Deployment to Rollout, we had to manually delete the Deployment Resource after applying the new Rollout Resource along with a new Preview Service Resource. Fortunately, Argo Rollouts does update the selector in the Active Service to point to the new Rollout Pods which shifts traffic away from the old Deployment Pods. Therefore, it is then safe to manually delete the Deployment Resource which then deletes the Deployment ReplicaSet and Pods.

**Comment by tomsanbear** [comment]
Awesome, thanks for your experience. Kind of the answer I expected, also good to know re: the service selector. 

I'm going to leave this open as I'm curious if automating this process is in the roadmap. Otherwise my question is answered!

Cheers.

**Comment by carlosdoordash** [comment]
We were also surprised that it didn't automatically delete the Deployment but then it made sense when you consider that the Argo Rollouts controller didn't create the Deployment in the first place.

I'd also like to add that we are actually using Helm Charts which helps to simplify the migration to just setting a boolean value on upgrade. We would then just need to run two helm upgrades. The first helm upgrade would install a chart that has both the Deployment Resource and Rollout Resource defined, so that the Rollout Resource can be applied without removing the Deployment Resource. The second helm upgrade would install a chart that would only have the Rollout Resource defined to delete the Deployment Resource.

**Comment by tomsanbear** [comment]
Ah that's a good insight actually. Would be an interesting option buy I guess there is the potential for disaster if it assumes it can delete.

Thanks again!
