### ISSUE TITLE
Add option for set suffix in canary pod name

### ISSUE THREAD

**Issue by oliveiraxavier** [argoproj/argo-rollouts#3894]
# Summary
During rollout, all pods have the same name and prefix. It visually it is not so quick to differentiate pods that are canary and stable. 

What change needs making?

It would be interesting to have a way for canary pods to have a suffix (eg rollout-deploy-canary-xxxxx-yyyy) while stable pods have rollout-deploy-xxxxx-yyyy. After everything was promoted, all pods would have rollouts -deploy-xxxxx-yyyy
# Use Cases

When would you use this?
In same cases, the k8s, want to see pods for rollouts in kubectl get pods or k9s

---

**Comment by zimmertr** [comment]
Can't you use [Ephemeral Metadata](https://argo-rollouts.readthedocs.io/en/stable/features/ephemeral-metadata/) and labels for this? EG: `kubectl get pods -n $NAMESPACE -l labelKey=labelValue`

**Comment by oliveiraxavier** [comment]
In my scenario, this doesn't suit me. For example, if you open a service with the same name in k9s, all pods will have the same name, visually (without filter label), it is not quick to know which is canary or which is stable

**Comment by mmcken3** [comment]
Pods cannot be renamed once created in kubernetes as the api would not allow it, so this would run into issues when it comes time to promote canary pods to stable pods depending on the rollout type chosen. But going based on the canary terminology I am assuming this is a canary release. Because whatever name is "canary" during the release, will suddenly become stable after the rollout finishes and will keep that replica set + pod name convention. 

You might could look at some sort of generic naming rotation, but depending on replica set history you have you might run into a situation where two replica sets have the same value

**Comment by oliveiraxavier** [comment]
Thanks for answers.
