### ISSUE TITLE
Add label to canary pod during analysis run

### ISSUE THREAD

**Issue by calerogers** [argoproj/argo-rollouts#433]
While using the web metric provider (Datadog) there is currently no way to create a monitor that only targets the canary pod. Ideally the rollouts controller would temporarily add a label or annotation to the pod during the analysis template run. This way the metrics consumed in the analysis are directly monitoring the canary pod health.

**Comment by moensch** [comment]
All pods will get the `pod-template-hash` label and you can use that to differentiate between stable and canary pods.

When you invoke an Analysis, you can pass args to reference the stable and canary has to your AnalysisTemplate. An example of that can be found here: https://argoproj.github.io/argo-rollouts/features/analysis/#experimentation-eg-mann-whitney-analysis

**Comment by calerogers** [comment]
I think using the `pod-template-hash` label could work with datadog. Our approach was configuring the datadog agent to add this label as a tag and configure a monitor to group by that tag. 

Doing this allowed each canary hash to have its own status. During the analysis run we could check on that specific hash status. The issue in this scenario is that we are unable to interpolate the `pod-template-hash` value (which needs to be passed in as an arg from your docs) into the `jsonPath`. We need to interpolate this value into the `jsonPath` because datadog sets the key in the returned json to the what the monitor is grouped by which is the hash.

The reason we cannot interpolate is because the jsonPath is evaluated before the args templating are resolved:
https://github.com/argoproj/argo-rollouts/blob/master/metricproviders/metricproviders.go#L58
This causes a `jsonPath` syntax error when attempting to interpolate an arg using `{{ arg.canary-hash }}`

```unrecognized character in action: U+007B '{'```

Any thoughts or suggestions on how to work around this?

**Comment by tomsanbear** [comment]
I've actually run into similar issue as well, my solution was to have my build auto-generate short lived datadog dashboards/configurations to view during a deployment. Now this is not ideal since there is a lot of co-dependence between my CI, CD and Monitoring Stacks. Like you were mentioning in the first bit of this issue, a nice to have would be adding custom argocd labels to pods, a la:
```
rollouts.argoproj.github.io/type: {canary/bluegreen/experiment}
...

```
This would also help with aggregating stats on how many canary releases are in progress, experiments status, fail rate across deployments (these are just off the top of my head)

**Comment by tsanterre-paypay** [comment]
Seems like this will be tracked via #455

**Comment by jessesuen** [comment]
`pod-template-hash` is the only way to do this today, but is inconvenient because:
 it is not predictable by a user for use in a pre-defined query.

> Seems like this will be tracked via #455

Correct. #455 is the feature which allows user-defined ephemeral labels, wile the rollout is in the middle of an update. I think we can close this one as dup.
