### ISSUE TITLE
Failed to create blue-green deployment rollout 

### ISSUE THREAD

**Issue by sakshi-bansal** [argoproj/argo-rollouts#513]
Failed to create the example blue-green deployment mentioned here https://argoproj.github.io/argo-rollouts/features/bluegreen/

**Steps**:
1. Create yaml file BlueGreen.yaml

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false

2. kubectl apply -f bluegreen.yaml

**Output**:
1. kubectl describe rollout 
Events:
  Type     Reason           Age                   From                 Message
  ----     ------           ----                  ----                 -------
  Warning  ServiceNotFound  89s (x14 over 4m13s)  rollouts-controller  Service "rollout-bluegreen-preview" is not found

If I understand correctly the service should get created by the rollout? However, it is unable to create the service.

**Other Details:**
Successfully deployed canary deployment.

**Comment by carlosdoordash** [comment]
Argo Rollouts doesn't create Service resources. Instead, you need to write the spec for the active and preview Service resources. You can then apply all three resources at the same time or just apply the Service resources before the Rollout resource.

It is true that the example in the docs cannot be applied as is because it doesn't include the specs for the two Service resources that the example references.

Any two Service specs that select your pods are sufficient.

For example, you could create the active service spec as type LoadBalancer for real traffic while creating a preview service spec as type ClusterIP assuming you only want to probe the preview service from within the k8s cluster.

In our case, we purposely create the preview service to listen on different ports than the active service. That way a service client can't accidentally send real traffic to a preview service.
