### ISSUE TITLE
kubectl argo rollouts undo rollout ROLLOUTNAME

### ISSUE THREAD

**Issue by notetook** [argoproj/argo-rollouts#575]
Hi, I've been progressing a PoC of Argo-rollouts.

If I want to roll back to the specific revision, how can I do it?
I cannot find a solution to resolve that.
Is it the only way to just apply the manifest of the specific revision?

In case of using `Deployment`, it is so easy: `kubectl rollout undo deploy $deploy_name --to-revision $specific_version`
I've tried this for `Rollout`, but it wasn't supported.

**Comment by jessesuen** [comment]
TBH, I consider kubectl rollback to be insufficient for a lot of cases, because it only thing it undoes, is a single Deployment. Many of the times, the thing that is desired to be rolled back is a combination of resources (Deployment + ConfigMap), or even other objects not related to the Deployment. If using GitOps, it would be better to to use your deployment tool (e.g. Argo CD) to perform rollbacks.

That said, I think an equivalent command in the plugin would be nice to have, if only for feature parity to Deployment.
