### ISSUE TITLE
Support HA in rollouts controller

### ISSUE THREAD

**Issue by rhysemmas** [argoproj/argo-rollouts#727]
# Summary

Adding support to the rollouts controller for HA, through the use of leadership elections. E.g:
https://tunein.engineering/implementing-leader-election-for-kubernetes-pods-2477deef8f13
https://carlosbecker.com/posts/k8s-leader-election
https://pkg.go.dev/k8s.io/client-go/tools/leaderelection

# Use Cases

When wanting to run multiple replicas of the rollouts controller, with the aim of making deployments/updates of rollouts less likely to be disrupted if a controller pod becomes unavailable.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by mmpei** [comment]
any update?

**Comment by jessesuen** [comment]
@mmpei yes, please feel free to work on it since this would come after a bunch of other v0.10 priorities for us.

**Comment by alexec** [comment]
I'm implementing for workflows. Should be able to give you test code to copy.

**Comment by alexec** [comment]
https://github.com/argoproj/argo/pull/4185

**Comment by dudadornelles** [comment]
There are no docs on upgrading argo-rollouts currently; is it fair to assume that upgrades will be disruptive for rollouts that are happening at that moment?

**Comment by jessesuen** [comment]
Upgrading rollouts is simply applying the new set of manifests. There are no special instructions

> is it fair to assume that upgrades will be disruptive for rollouts that are happening at that moment?

For the time duration where the rollout controller is down (this should only take a few seconds), Rollout resources which are in the middle of upgrades will not make progress. When the rollout controller comes back up, the updates will resume and continue where they left off. This is the same time as rescheduling the pod say in the event that the underlying node went away.

But currently since the controller is not serving any traffic, the need for HA in the controller is less important than say a web service which requires 24/7 uptime to service requests. So long as the controller can quickly come back up, upgrades should be unnoticeable.

**Comment by dudadornelles** [comment]
Thanks a lot for the reply, I can see how HA is not that important for the controller given rollouts can resume as soon as the controller is back.

**Comment by samschlegel** [comment]
> But currently since the controller is not serving any traffic, the need for HA in the controller is less important than say a web service which requires 24/7 uptime to service requests. 

It is less, but since the controller is responsible for updating the ReplicaSet replicas based on the Rollout replicas, this means that if a HorizonalPodAutoscaler needs to scale up a webservice to handle increased load while the controller is down, this could lead ultimately to a service failure.

**Comment by samschlegel** [comment]
Would this be as simple as running [manager.Run](https://github.com/argoproj/argo-rollouts/blob/master/cmd/rollouts-controller/main.go#L173) in the `OnStartedLeading` callback?

**Comment by caoyang001** [comment]
@jessesuen Hi，Could you please review this PR？thanks：https://github.com/argoproj/argo-rollouts/pull/1246

**Comment by jessesuen** [comment]
Hey, thanks for implementing this! After I push v1.0.2 out the door (should happen today), will look into this and other v1.1 pull requests.

**Comment by harikrongali** [comment]
@huikang can we close this?

**Comment by huikang** [comment]
> @huikang can we close this?

Thanks for checking. Yeah, this one can be closed now.
