### ISSUE TITLE
provide health check for argo-rollout controller

### ISSUE THREAD

**Issue by soulseen** [argoproj/argo-rollouts#891]
# Summary

provide a health check for argo-rollout controller.
according to the install file https://github.com/argoproj/argo-rollouts/blob/master/manifests/install.yaml#L15034, it does not have the readiness and liveness probes.

**Comment by soulseen** [comment]
@jessesuen pls take a look at this issue. thanks a lot.

**Comment by jessesuen** [comment]
Since the rollout controller is not a web service (aside from metrics endpoint), there is no need for an indicator to Kubernetes that the container is ready to receive traffic and added to the Endpoints list. What are you expecting in terms of a readiness probe?

Similarly, liveness probes are only intended to be used if the container is in an unrecoverable state which can only be fixed with a termination of the container (e.g. a deadlock). Liveness probes [are even be considered dangerous](https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html#:~:text=A%20wrong%20livenessProbe%20setting%20can,K3s%2BACME%20rate%20limits).

Liveness and readiness have their uses, but they should not be used unless there is a good reason.
